sudo: required
services:
  - docker

before_install:
  - docker build -t k00lbean/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run k00lbean/react-test npm test -- --coverage

after_success:
  - docker build -t k00lbean/multi-client ./client
  - docker build -t k00lbean/multi-nginx ./nginx
  - docker build -t k00lbean/multi-server ./server
  - docker build -t k00lbean/multi-worker ./worker
  ### Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ### Take those imags and push them to docker hub
  - docker push k00lbean/multi-client
  - docker push k00lbean/multi-nginx
  - docker push k00lbean/multi-server
  - docker push k00lbean/multi-worker